AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-zt'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test20-wus2'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://dev.azure.com/cykreng/'
ORG: 'azuredevops'
ASELOCATION: 'West US 2'