AZURE_LOCATION: "westeurope"
RESOURCE_NAME_PREFIX: "asev3-cs"
ENVIRONMENT_TAG: "dev"
DEPLOYMENT_NAME: "test3-we"
VMAZDEVOPS_USERNAME: "adoagent"
WMAZDEVOPS_PW: "6N?N)&#Ff"JFbuCh"
AZDEVOPS_ACCT: "cykreng"
