AZURE_LOCATION: "westeurope"
RESOURCE_NAME_PREFIX: "asev3-cs"
ENVIRONMENT_TAG: "dev"
DEPLOYMENT_NAME: "test2-we"
VMAZDEVOPS_USERNAME: "adoagent"
VMAZDEVOPS_PW: "6N?N)&#Ff"JFbuCh"
AZDEVOPS_ACCT: "https://dev.azure.com/cykreng/"