AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-zt'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test80-wus2'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://dev.azure.com/cykreng/'
CICD_AGENT_TYPE: 'azuredevops'