AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-cs3'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test6-wus2'
VMAZDEVOPS_USERNAME: 'adoagent'
VMAZDEVOPS_PW: 'dN~bH9UG'
AZDEVOPS_ACCT: 'https://dev.azure.com/cykreng/'