AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-cs4'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test7-wus2'
VMAZDEVOPS_USERNAME: 'adoagent'
VMAZDEVOPS_PW: 'dN~bH9UG'
AZDEVOPS_ACCT: 'https://dev.azure.com/cykreng/'