AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-cs2'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test5-wus2'
VMAZDEVOPS_USERNAME: 'adoagent'
VMAZDEVOPS_PW: 'dN~bH9U\r.Qz}X\G'
AZDEVOPS_ACCT: 'https://dev.azure.com/cykreng/'