AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asev3-cs7'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'test10-wus2'
VMAZDEVOPS_USERNAME: 'adoagent'
VMAZDEVOPS_PW: 'dN~bH9UG'
AZDEVOPS_ACCT: 'https://dev.azure.com/cykreng/'
ASELOCATION: 'West US 2'