AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'demo-prefix'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'demo'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'