name: 'AzureBicepDeploy'
 
on:
  workflow_dispatch:

  push:
    branches:
    - main
  pull_request:
 
jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./deployment/bicep

  build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Install yq to parse yaml file
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
    
      - name: Parse config.yaml as output to GitHub Actions matrix
        run: |
          echo "config=$(yq e ./deployment/bicep/config.yml -j -I=0)" >> $GITHUB_ENV  

      - name: Write deployment information to log
        run: |
          echo "Deploying to ${{ fromJson(env.config).AZURE_LOCATION }} with name prefix ${{ fromJson(env.config).ENVIRONMENT_TAG }}"

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ fromJson(env.config).AZURE_LOCATION }}
          deploymentName:  ${{ fromJson(env.config).DEPLOYMENT_NAME }}
          template: ./deployment/bicep/main.bicep
          parameters: workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }}