name: 'ASEv3 Terraform'

on:
  workflow_dispatch:

  push:
    branches:
    #- main 
    - jin/41/path-for-workflow-trigger-include-iac
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'

  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'

env:
  modulePath: 'reference-implementations/LOB-ILB-ASEv3/terraform'

jobs:
  # validate_terraform:
  #   name: "Validate Terraform files"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v2

  #     - name: Validate that bicep builds
  #       run: az bicep build -f main.bicep
  #       working-directory: ${{ env.modulePath }}


  build-and-deploy:
    name: "Deploy Terraform templates"
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: | 
          # Parse Azure secret into Terraform variables
          $servicePrincipal = ($env:AZURE_CREDENTIALS | ConvertFrom-Json)
          $env:ARM_CLIENT_ID = $servicePrincipal.clientId
          $env:ARM_CLIENT_SECRET = $servicePrincipal.clientSecret
          $env:ARM_SUBSCRIPTION_ID = $env.AZURE_SUBSCRIPTION
          $env:ARM_TENANT_ID = $servicePrincipal.tenantId
          
          # Save environment variable setup for subsequent steps
          Get-ChildItem -Path Env: -Recurse -Include ARM_*,TF_VAR_* | ForEach-Object {Write-Output "$($_.Name)=$($_.Value)"} >> $env:GITHUB_ENV
        shell: pwsh

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Setup Terraform on agent
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.8

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Validate
        working-directory: ${{ env.modulePath }}
        run: |
          terraform init
          terraform validate

      - name: Write deployment information to log
        working-directory: ${{ env.modulePath }}
        run: terraform plan -var-file="${{ env.modulePath }}/Parameters/uat.tfvars"

        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        working-directory: ${{ env.modulePath }}
        run: terraform apply -auto-approve -input=false -var-file="${{ env.modulePath }}/Parameters/uat.tfvars"
