name: 'ASEv3 Terraform'

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy infrastructure (default: false)'
        required: false
        default: false
  push:
    branches:
    # - main
      - jin/41/path-for-workflow-trigger-include-iac
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'

  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'

env:
  modulePath: 'reference-implementations/LOB-ILB-ASEv3/terraform'

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: | 
          # Parse Azure secret into Terraform variables
          $servicePrincipal = ($env:AZURE_CREDENTIALS | ConvertFrom-Json)
          $env:ARM_CLIENT_ID = $servicePrincipal.clientId
          $env:ARM_CLIENT_SECRET = $servicePrincipal.clientSecret
          $env:ARM_SUBSCRIPTION_ID = $env:AZURE_SUBSCRIPTION
          $env:ARM_TENANT_ID = $servicePrincipal.tenantId
          
          # Save environment variable setup for subsequent steps
          Get-ChildItem -Path Env: -Recurse -Include ARM_*,TF_VAR_* | ForEach-Object {Write-Output "$($_.Name)=$($_.Value)"} >> $env:GITHUB_ENV
        shell: pwsh

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Setup Terraform on agent
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.8

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  validate_and_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Validate
        working-directory: ${{ env.modulePath }}
        run: |
          terraform init
          terraform validate


      - name: Terraform Plan Destroy
        id: tfplandestroy
        if: ${{ github.event.inputs.destroy == 'true' }}
        working-directory: ${{ env.modulePath }}
        continue-on-error: true
        run: |
          terraform plan -destroy \
            -var-file="Parameters/uat.tfvars" \
            -out-file="./asev3-${{github.run_number}}.tfplan"

      - name: Terraform Plan
        id: tfplan
        if: ${{ github.event.inputs.destroy == 'false' }}
        working-directory: ${{ env.modulePath }}
        continue-on-error: true
          terraform plan \
            -var-file="Parameters/uat.tfvars" \
            -out-file="./asev3-${{github.run_number}}.tfplan"

      - name: Upload TF Plan
        uses: actions/upload-artifact@v3
        with:
          name: "asev3-${{github.run_number}}.tfplan"
          path: "./tfplan/asev3-${{github.run_number}}.tfplan"
          if-no-files-found: error
          retention-days: 1

  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        needs: validate
        working-directory: ${{ env.modulePath }}
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            asev3-${{github.run_number}}.tfplan
