name: 'Scenario 1: Bicep Multi-Tenant ASEv3 Secure Baseline'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - refactor/iac-cicd
    paths:
      - '.github/workflows/_template.bicep.yml'
      - '.github/workflows/scenario1.bicep.yml'
      - 'scenarios/secure-baseline-multitenant/bicep/**.bicep'
      - 'scenarios/secure-baseline-multitenant/bicep/parameters/ase-multitenant.parameters.jsonc'
      - '!scenarios/secure-baseline-multitenant/**.md'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_template.bicep.yml'
      - '.github/workflows/scenario1.bicep.yml'
      - 'scenarios/secure-baseline-multitenant/bicep/**.bicep'
      - 'scenarios/secure-baseline-multitenant/bicep/parameters/ase-multitenant.parameters.jsonc'
      - '!scenarios/secure-baseline-multitenant/**.md'

permissions:
  id-token: write
  contents: read

env:
  deploymentPath: 'scenarios/secure-baseline-multitenant/bicep/main.bicep'
  scenarioName: 'ase-multitenant'
  region: 'westus2'

jobs:
  prepare-environment:
    name: 'Prepare CICD Environment for Bicep Workflow'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    outputs:
      region: ${{ env.region }}
      modulePath: ${{ env.deploymentPath }}
      bicepParamPath: ${{ env.deploymentPath }}/parameters/${{ env.scenarioName }}.parameters.jsonc

  call-workflow-passing-data:
    name: 'Bicep CICD'
    needs: 
    - prepare-environment
    uses: ./.github/workflows/.template.bicep.yml
    with:
      region: ${{ needs.prepare-environment.outputs.region }}
      modulePath: ${{ needs.prepare-environment.outputs.modulePath }}
      bicepParamPath: ${{ needs.prepare-environment.outputs.bicepParamPath }}
      # Ensure this value is a boolean
      destroy: ${{ github.event.inputs.destroy == 'true' }}
    secrets: inherit
