name: 'Terraform Dependencies'

on:
  workflow_dispatch:
  push:
    branches:
    # - main
    - jin/41/path-for-workflow-trigger-include-iac
    paths:
      - '.github/workflows/terraform-dependencies.yml'
env:
  location: 'westus2'
  resource_prefix: "backend-appsrvc"
  environment: "dev"
  suffix: "001"

jobs:
  provision-infrastructure-dependencies:
    name: "Create storage account and container for Terraform state"
    runs-on: ubuntu-latest
    steps:
      # Login Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Resource Group
        run: |
          rg_name=${{ env.resource_prefix }}-${{ env.environment }}-${{env.location}}-${{ env.suffix }}
          if [ $(az group exists --name $rg_name) = false ]; then
            az group create \
              --name $rg_name \
              --location ${{ env.location }} 
          fi
      
      - name: Create Storage Account
        run: |
          rg_name=${{ env.resource_prefix }}-${{ env.environment }}-${{env.location}}-${{ env.suffix }}
          st_name_prefix="$(echo st${{ env.resource_prefix }}${{ env.environment }} | cut -c1-15)"
          st_name_suffix="$(echo ${{ env.location }}${{ env.suffix }} | cut -c1-11)"
          formatted_st_name="${st_name_prefix//-/}${st_name_suffix}"

          if [ $(az storage account check-name --name $formatted_st_name --query nameAvailable) ]; then
            az storage account create \
              --name $formatted_st_name \
              --resource-group $rg_name \
              --location ${{ env.location }} \
              --subscription ${{ secrets.AZURE_SUBSCRIPTION }} \
              --sku Standard_LRS

            az storage container create \
              --name tfstate \
              --account-name $formatted_st_name
          fi

