name: 'Terraform Dependencies'

on:
  workflow_dispatch:

env:
  location: 'westus2'
  resource_prefix: "backend-appsrvc"
  environment: "dev"
  suffix: "001"
  container_name: "tfstate"

jobs:
  provision-infrastructure-dependencies:
    name: "Create storage account and container for Terraform state"
    runs-on: ubuntu-latest
    steps:
      # Login Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Resource Group
        id: rg
        run: |
          rg_name=${{ env.resource_prefix }}-${{ env.environment }}-${{env.location}}-${{ env.suffix }}
          if [ $(az group exists --name $rg_name) = false ]; then
            az group create \
              --name $rg_name \
              --location ${{ env.location }} 
          fi
          echo ::set-output name=rg_name::$rg_name
      
      - name: Create Storage Account
        run: |
          # Format name to 24 char limit, lowercase, and remove dashes
          st_name_prefix="$(echo st${{ env.resource_prefix }}${{ env.environment }} | cut -c1-15)"
          st_name_suffix="$(echo ${{ env.location }}${{ env.suffix }} | cut -c1-11)"
          formatted_st_name="$(echo ${st_name_prefix//-/}${st_name_suffix} | tr '[:upper:]' '[:lower:]')"

          if [ $(az storage account check-name --name $formatted_st_name --query nameAvailable) ]; then
            az storage account create \
              --name $formatted_st_name \
              --resource-group ${{ steps.rg.outputs.rg_name }} \
              --location ${{ env.location }} \
              --subscription ${{ secrets.AZURE_SUBSCRIPTION }} \
              --sku Standard_LRS

            az storage container create \
              --name ${{ env.container_name }} \
              --account-name $formatted_st_name
          fi

